services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PUBLIC_API_URL=${PUBLIC_API_URL:-http://localhost:3000/api/v1}
        - PUBLIC_KIORA_API_KEY=${PUBLIC_KIORA_API_KEY:-kiosk_secret_key_2024}
        - PUBLIC_WEGLOT_API_KEY=${PUBLIC_WEGLOT_API_KEY:-}
        - PUBLIC_SENTRY_DSN=${PUBLIC_SENTRY_DSN:-https://939080ed4cff9f9de326409db475b4f1@o4511345952686080.ingest.us.sentry.io/4511346045091840}

    container_name: kiora_frontend_app
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - kiora-public-net
      - kiora-backend-net

networks:
  kiora-public-net:
    external: true
  kiora-backend-net:
    external: true
